services:
  postgresql:
    image: postgres:latest  
    platform: linux/amd64
    restart: always
    ports:
      - '5432:5432'  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_USER=${POSTGRES_USER}         
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data 

volumes:
  postgresql:  
